# Generated by Django 5.2.6 on 2026-01-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='max_storage_gb',
            field=models.FloatField(default=1.0),
        ),
    ]
