# Generated by Django 5.2.10 on 2026-01-14 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentskill',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.agentprofile'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='shift_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.shifttype'),
        ),
        migrations.AddField(
            model_name='agentskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.skill'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='skills',
            field=models.ManyToManyField(through='agents.AgentSkill', to='agents.skill'),
        ),
        migrations.AddField(
            model_name='team',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.team'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.team'),
        ),
        migrations.AlterUniqueTogether(
            name='agentskill',
            unique_together={('agent', 'skill')},
        ),
    ]
