# Generated by Django 5.2.10 on 2026-01-16 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shifttype',
            name='paid_hours',
        ),
        migrations.CreateModel(
            name='ShiftTemplateActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('WORK', 'Work'), ('BREAK', 'Break'), ('LUNCH', 'Lunch')], max_length=20)),
                ('start_offset_minutes', models.IntegerField(help_text='Minutes from shift start')),
                ('duration_minutes', models.IntegerField()),
                ('shift_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_activities', to='agents.shifttype')),
            ],
            options={
                'ordering': ['start_offset_minutes'],
            },
        ),
    ]
