# Generated by Django 5.2.10 on 2026-01-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_department_team_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='managed_teams',
            field=models.ManyToManyField(blank=True, related_name='managers', to='agents.team'),
        ),
    ]
