# Generated by Django 5.2.10 on 2026-01-14 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_initial'),
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('generic', 'Generic API'), ('avaya', 'Avaya AES'), ('genesys', 'Genesys PureCloud'), ('cisco', 'Cisco Finesse'), ('alcatel', 'Alcatel-Lucent')], default='generic', max_length=20)),
                ('api_url', models.URLField(blank=True, help_text='Endpoint to push/pull data', null=True)),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RealTimeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(choices=[('agent_state', 'Agent State Change'), ('call', 'Call Event'), ('queue', 'Queue Metric')], max_length=20)),
                ('agent_id', models.CharField(blank=True, max_length=50, null=True)),
                ('queue_id', models.CharField(blank=True, max_length=50, null=True)),
                ('payload', models.JSONField(help_text='Normalized Event Data')),
                ('raw_data', models.JSONField(blank=True, help_text='Raw Vendor Data', null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RealTimeAgentState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=50)),
                ('since', models.DateTimeField()),
                ('reason_code', models.CharField(blank=True, max_length=50, null=True)),
                ('agent_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='live_state', to='agents.agentprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
