# Generated by Django 5.2.10 on 2026-01-17 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0002_integrationconfig_realtimeevent_realtimeagentstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='customer_number',
            field=models.CharField(blank=True, help_text='Caller Phone Number', max_length=50, null=True),
        ),
    ]
