# Generated by Django 5.2.6 on 2026-01-16 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0002_notification_shiftchangerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('WORK', 'Work'), ('BREAK', 'Break'), ('LUNCH', 'Lunch'), ('MEETING', 'Meeting'), ('TRAINING', 'Training')], max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='shifts.shift')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
