# Generated by Django 5.2.10 on 2026-01-16 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_remove_shifttype_paid_hours_shifttemplateactivity'),
        ('shifts', '0003_shiftactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='shift_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.shifttype'),
        ),
    ]
